-- =========================================================
-- Team Kanban - Complex Sample Data
-- Demo dataset for CT214H project
-- Default login password for all users: ngthtrong
-- =========================================================

USE kanban_db;

-- Password hash for plaintext: ngthtrong
-- Generated by PHP password_hash(..., PASSWORD_BCRYPT)
-- Reused for all demo users to simplify login during presentation.

INSERT INTO users (username, email, password, full_name, avatar) VALUES
('ngthtrong1', 'ngthtrong1@example.com', '$2y$10$hnBT7BUO1mcwJZ67pOy/Z.bF69vp35enRPz5Su492C5jxagYc.k7e', 'Nguyen Thanh Trong 1', NULL),
('ngthtrong2', 'ngthtrong2@example.com', '$2y$10$hnBT7BUO1mcwJZ67pOy/Z.bF69vp35enRPz5Su492C5jxagYc.k7e', 'Nguyen Thanh Trong 2', NULL),
('ngthtrong3', 'ngthtrong3@example.com', '$2y$10$hnBT7BUO1mcwJZ67pOy/Z.bF69vp35enRPz5Su492C5jxagYc.k7e', 'Nguyen Thanh Trong 3', NULL),
('ngthtrong4', 'ngthtrong4@example.com', '$2y$10$hnBT7BUO1mcwJZ67pOy/Z.bF69vp35enRPz5Su492C5jxagYc.k7e', 'Nguyen Thanh Trong 4', NULL),
('ngthtrong5', 'ngthtrong5@example.com', '$2y$10$hnBT7BUO1mcwJZ67pOy/Z.bF69vp35enRPz5Su492C5jxagYc.k7e', 'Nguyen Thanh Trong 5', NULL),
('ngthtrong6', 'ngthtrong6@example.com', '$2y$10$hnBT7BUO1mcwJZ67pOy/Z.bF69vp35enRPz5Su492C5jxagYc.k7e', 'Nguyen Thanh Trong 6', NULL),
('ngthtrong7', 'ngthtrong7@example.com', '$2y$10$hnBT7BUO1mcwJZ67pOy/Z.bF69vp35enRPz5Su492C5jxagYc.k7e', 'Nguyen Thanh Trong 7', NULL),
('ngthtrong8', 'ngthtrong8@example.com', '$2y$10$hnBT7BUO1mcwJZ67pOy/Z.bF69vp35enRPz5Su492C5jxagYc.k7e', 'Nguyen Thanh Trong 8', NULL),
('ngthtrong9', 'ngthtrong9@example.com', '$2y$10$hnBT7BUO1mcwJZ67pOy/Z.bF69vp35enRPz5Su492C5jxagYc.k7e', 'Nguyen Thanh Trong 9', NULL),
('ngthtrong10', 'ngthtrong10@example.com', '$2y$10$hnBT7BUO1mcwJZ67pOy/Z.bF69vp35enRPz5Su492C5jxagYc.k7e', 'Nguyen Thanh Trong 10', NULL);

INSERT INTO projects (owner_id, project_name, description, project_code, is_archived, archived_at) VALUES
(1, 'CT214H Kanban Core', 'Core features for auth, project and task management', 'NGT10001', 0, NULL),
(2, 'Mobile UI Revamp', 'Improve responsive layout and accessibility', 'NGT10002', 0, NULL),
(3, 'Database Optimization', 'Search/filter tuning and index optimization', 'NGT10003', 0, NULL),
(4, 'Report and Presentation', 'LaTeX report, diagrams and demo assets', 'NGT10004', 0, NULL),
(5, 'Automation and QA', 'Smoke tests and release checklist', 'NGT10005', 0, NULL),
(6, 'Legacy Migration Lab', 'Archived sandbox for old migration experiments', 'NGT10006', 1, '2026-04-05 10:00:00'),
(7, 'Search Analytics Dashboard', 'Dashboard for search usage and filter metrics', 'NGT10007', 0, NULL),
(8, 'API Hardening Sprint', 'Improve API safety, validation and error handling', 'NGT10008', 0, NULL),
(9, 'Kanban Automation Bots', 'Task reminders and workflow automation experiments', 'NGT10009', 0, NULL),
(10, 'Intern Onboarding Board', 'Training board for new teammates', 'NGT10010', 0, NULL),
(1, 'Documentation Translation', 'Translate docs and standardize terminology', 'NGT10011', 0, NULL),
(2, 'Release Candidate 1', 'Stabilization and bug-fix sprint for RC1', 'NGT10012', 1, '2026-04-09 09:00:00');

INSERT INTO project_members (project_id, user_id, role) VALUES
-- Project 1
(1, 1, 'owner'),
(1, 2, 'member'),
(1, 3, 'member'),
(1, 4, 'member'),
(1, 5, 'member'),
(1, 6, 'member'),
(1, 7, 'member'),
(1, 8, 'member'),

-- Project 2
(2, 2, 'owner'),
(2, 1, 'member'),
(2, 3, 'member'),
(2, 4, 'member'),
(2, 5, 'member'),
(2, 9, 'member'),
(2, 10, 'member'),

-- Project 3
(3, 3, 'owner'),
(3, 1, 'member'),
(3, 2, 'member'),
(3, 6, 'member'),
(3, 7, 'member'),
(3, 8, 'member'),
(3, 9, 'member'),

-- Project 4
(4, 4, 'owner'),
(4, 1, 'member'),
(4, 5, 'member'),
(4, 6, 'member'),
(4, 7, 'member'),
(4, 10, 'member'),

-- Project 5
(5, 5, 'owner'),
(5, 2, 'member'),
(5, 3, 'member'),
(5, 8, 'member'),
(5, 9, 'member'),
(5, 10, 'member'),

-- Project 6 (archived project)
(6, 6, 'owner'),
(6, 1, 'member'),
(6, 4, 'member'),
(6, 7, 'member'),

-- Project 7
(7, 7, 'owner'),
(7, 1, 'member'),
(7, 2, 'member'),
(7, 3, 'member'),
(7, 5, 'member'),
(7, 8, 'member'),
(7, 10, 'member'),

-- Project 8
(8, 8, 'owner'),
(8, 1, 'member'),
(8, 4, 'member'),
(8, 6, 'member'),
(8, 7, 'member'),
(8, 9, 'member'),

-- Project 9
(9, 9, 'owner'),
(9, 2, 'member'),
(9, 3, 'member'),
(9, 5, 'member'),
(9, 7, 'member'),
(9, 10, 'member'),

-- Project 10
(10, 10, 'owner'),
(10, 1, 'member'),
(10, 4, 'member'),
(10, 6, 'member'),
(10, 8, 'member'),

-- Project 11
(11, 1, 'owner'),
(11, 2, 'member'),
(11, 3, 'member'),
(11, 4, 'member'),
(11, 5, 'member'),
(11, 6, 'member'),
(11, 7, 'member'),
(11, 8, 'member'),
(11, 9, 'member'),
(11, 10, 'member'),

-- Project 12 (archived project)
(12, 2, 'owner'),
(12, 1, 'member'),
(12, 3, 'member'),
(12, 4, 'member'),
(12, 5, 'member');

INSERT INTO project_join_requests (project_id, user_id, status, requested_at, responded_at) VALUES
(1, 9, 'pending',  '2026-04-11 09:00:00', NULL),
(1, 10, 'rejected', '2026-04-10 10:15:00', '2026-04-10 15:20:00'),
(2, 6, 'pending',  '2026-04-12 08:30:00', NULL),
(2, 8, 'approved', '2026-04-08 14:05:00', '2026-04-08 18:10:00'),
(3, 5, 'pending',  '2026-04-12 16:45:00', NULL),
(4, 2, 'rejected', '2026-04-09 11:10:00', '2026-04-09 12:40:00'),
(4, 3, 'pending',  '2026-04-12 13:00:00', NULL),
(5, 1, 'approved', '2026-04-07 09:20:00', '2026-04-07 17:50:00'),
(5, 6, 'pending',  '2026-04-13 08:05:00', NULL),
(6, 10, 'pending', '2026-04-06 10:00:00', NULL),
(7, 4, 'pending',  '2026-04-13 09:10:00', NULL),
(7, 6, 'approved', '2026-04-10 08:00:00', '2026-04-10 11:20:00'),
(8, 2, 'pending',  '2026-04-13 11:45:00', NULL),
(8, 5, 'rejected', '2026-04-09 13:00:00', '2026-04-09 16:00:00'),
(9, 1, 'pending',  '2026-04-12 10:30:00', NULL),
(9, 6, 'approved', '2026-04-08 09:30:00', '2026-04-08 17:15:00'),
(10, 3, 'pending', '2026-04-13 14:20:00', NULL),
(11, 6, 'rejected', '2026-04-11 12:15:00', '2026-04-11 13:40:00'),
(11, 8, 'pending', '2026-04-13 15:00:00', NULL),
(12, 9, 'pending', '2026-04-09 10:05:00', NULL);

INSERT INTO tasks (
	project_id,
	assigned_to,
	task_title,
	description,
	column_status,
	priority,
	due_date,
	attachment_path,
	is_archived,
	archived_at
) VALUES
-- Project 1 tasks
(1, 2, 'Setup auth flow', 'Finalize login/logout flow and guard middleware', 'todo', 'high', '2026-04-20', NULL, 0, NULL),
(1, 1, 'Implement login API', 'Polish JSON response and error handling', 'in_progress', 'high', '2026-04-18', NULL, 0, NULL),
(1, 3, 'Register form validation', 'Add client and server validation rules', 'done', 'medium', '2026-04-10', 'validation-rules.docx', 0, NULL),
(1, NULL, 'Session timeout guard', 'Handle expired session and redirect safely', 'todo', 'medium', '2026-04-22', NULL, 0, NULL),
(1, 4, 'Avatar upload endpoint', 'Support image upload for profile avatar', 'in_progress', 'medium', '2026-04-21', 'avatar-api.pdf', 0, NULL),
(1, 5, 'Password reset research', 'Collect options for future enhancement', 'todo', 'low', '2026-04-25', NULL, 0, NULL),
(1, 7, 'Dashboard widget cleanup', 'Refactor widget rendering and spacing', 'done', 'low', '2026-04-09', NULL, 0, NULL),
(1, 8, 'Archive old draft tasks', 'Move outdated draft tasks into archive', 'done', 'medium', '2026-04-08', NULL, 1, '2026-04-11 15:00:00'),

-- Project 2 tasks
(2, 9, 'Responsive navbar polish', 'Tune mobile nav and breakpoint behavior', 'todo', 'medium', '2026-04-19', NULL, 0, NULL),
(2, 2, 'Kanban card compact mode', 'Add compact card style for smaller screens', 'in_progress', 'high', '2026-04-17', NULL, 0, NULL),
(2, 10, 'Color accessibility audit', 'Review contrast for all key UI elements', 'done', 'high', '2026-04-12', 'accessibility-checklist.pdf', 0, NULL),
(2, NULL, 'Modal keyboard navigation', 'Support keyboard shortcuts and focus trap', 'todo', 'high', '2026-04-23', NULL, 0, NULL),
(2, 1, 'Empty-state illustrations', 'Prepare placeholders for no-data sections', 'in_progress', 'low', '2026-04-24', NULL, 0, NULL),
(2, 3, 'Member badge redesign', 'Update style for owner/member badges', 'done', 'medium', '2026-04-11', NULL, 0, NULL),
(2, 4, 'Dark-mode spike', 'Prototype dark mode and collect feedback', 'todo', 'low', '2026-04-27', NULL, 0, NULL),

-- Project 3 tasks
(3, 3, 'Add composite indexes', 'Create indexes for project/status/archive columns', 'in_progress', 'high', '2026-04-16', NULL, 0, NULL),
(3, 6, 'Query plan baseline', 'Capture baseline EXPLAIN plans for key endpoints', 'done', 'medium', '2026-04-07', 'query-plan.xlsx', 0, NULL),
(3, 1, 'Pagination SQL tuning', 'Optimize LIMIT/OFFSET query path', 'todo', 'high', '2026-04-20', NULL, 0, NULL),
(3, 2, 'Search by assignee plus status', 'Verify combined filtering with AND logic', 'done', 'high', '2026-04-13', NULL, 0, NULL),
(3, NULL, 'Due date filter regression', 'Retest due_date_from and due_date_to combinations', 'todo', 'medium', '2026-04-21', NULL, 0, NULL),
(3, 7, 'Archive filter consistency', 'Ensure archived tasks are excluded by default', 'in_progress', 'medium', '2026-04-18', NULL, 0, NULL),
(3, 8, 'Seed data generator v2', 'Improve seed script for richer demo scenarios', 'todo', 'low', '2026-04-26', NULL, 0, NULL),
(3, 9, 'Backup restore drill', 'Run backup/restore verification for kanban_db', 'done', 'low', '2026-04-06', NULL, 0, NULL),

-- Project 4 tasks
(4, 4, 'Write chapter 1 draft', 'Complete introduction and objectives section', 'done', 'medium', '2026-04-05', 'chapter1-draft.docx', 0, NULL),
(4, 1, 'Update ERD diagram', 'Adjust entities and relationship notes', 'in_progress', 'high', '2026-04-17', NULL, 0, NULL),
(4, 10, 'Add UC6 sequence flow', 'Describe search/filter request sequence', 'todo', 'high', '2026-04-19', NULL, 0, NULL),
(4, NULL, 'Slide deck v1', 'Prepare first version of presentation slides', 'todo', 'medium', '2026-04-22', NULL, 0, NULL),
(4, 6, 'Demo script checklist', 'Create end-to-end demo flow checklist', 'in_progress', 'medium', '2026-04-18', NULL, 0, NULL),
(4, 7, 'Capture screenshots set A', 'Collect screenshots for report appendix', 'todo', 'low', '2026-04-24', NULL, 0, NULL),

-- Project 5 tasks
(5, 5, 'CI lint command docs', 'Document lint commands for PHP and SQL checks', 'todo', 'medium', '2026-04-20', NULL, 0, NULL),
(5, 2, 'API smoke test collection', 'Build quick smoke tests for main endpoints', 'in_progress', 'high', '2026-04-18', NULL, 0, NULL),
(5, 10, 'Upload file boundary test', 'Test file size and extension validation', 'done', 'high', '2026-04-12', 'upload-test-report.pdf', 0, NULL),
(5, 3, 'Join request edge cases', 'Cover duplicate and invalid request flows', 'todo', 'high', '2026-04-21', NULL, 0, NULL),
(5, 8, 'Permission matrix test', 'Verify owner/member permissions by action', 'in_progress', 'medium', '2026-04-19', NULL, 0, NULL),
(5, NULL, 'Release checklist draft', 'Create checklist before final submission', 'todo', 'low', '2026-04-25', NULL, 0, NULL),

-- Project 6 tasks (archived project, archived tasks)
(6, 6, 'Legacy login adapter', 'Bridge old auth model to current API', 'done', 'medium', '2026-03-20', NULL, 1, '2026-04-01 09:30:00'),
(6, 1, 'Legacy schema import', 'Import old schema and map compatibility gaps', 'done', 'high', '2026-03-22', NULL, 1, '2026-04-02 10:10:00'),
(6, 4, 'Compatibility shim cleanup', 'Remove temporary compatibility code paths', 'done', 'medium', '2026-03-25', NULL, 1, '2026-04-03 11:45:00'),
(6, NULL, 'Deprecated endpoint map', 'List and mark old endpoints to retire', 'done', 'low', '2026-03-28', NULL, 1, '2026-04-03 11:50:00'),

-- Project 7 tasks
(7, 7, 'Define metric dictionary', 'Standardize names for search and filter metrics', 'in_progress', 'high', '2026-04-18', NULL, 0, NULL),
(7, 1, 'Daily active users chart', 'Build chart for DAU of search page', 'todo', 'medium', '2026-04-21', NULL, 0, NULL),
(7, 2, 'Query latency panel', 'Track average API latency by endpoint', 'todo', 'high', '2026-04-19', NULL, 0, NULL),
(7, 8, 'Top keywords table', 'List top searched keywords by frequency', 'done', 'medium', '2026-04-11', 'top-keywords.xlsx', 0, NULL),
(7, NULL, 'Retention segment mock', 'Draft retention segment view for dashboard', 'todo', 'low', '2026-04-26', NULL, 0, NULL),

-- Project 8 tasks
(8, 8, 'Input validation matrix', 'Enumerate all request validation rules', 'in_progress', 'high', '2026-04-17', NULL, 0, NULL),
(8, 1, 'Standard API error contract', 'Unify error payload shape across endpoints', 'todo', 'high', '2026-04-20', NULL, 0, NULL),
(8, 4, 'Rate-limit policy draft', 'Define rate-limit policy for public routes', 'todo', 'medium', '2026-04-23', NULL, 0, NULL),
(8, 6, 'Audit invalid status handling', 'Retest invalid enum values for task status', 'done', 'medium', '2026-04-12', NULL, 0, NULL),
(8, 9, 'Security checklist v1', 'Compile checklist for API hardening phase', 'done', 'low', '2026-04-10', 'api-security-checklist.pdf', 0, NULL),

-- Project 9 tasks
(9, 9, 'Reminder bot command set', 'Define commands for due-date reminders', 'todo', 'medium', '2026-04-22', NULL, 0, NULL),
(9, 2, 'Webhook retry strategy', 'Implement retry policy for outbound webhooks', 'in_progress', 'high', '2026-04-18', NULL, 0, NULL),
(9, 3, 'Bot notification template', 'Create message templates for task events', 'done', 'low', '2026-04-11', NULL, 0, NULL),
(9, 7, 'Cron scheduler benchmark', 'Benchmark scheduler interval and CPU usage', 'todo', 'medium', '2026-04-24', NULL, 0, NULL),
(9, NULL, 'Automation fallback notes', 'Document manual fallback when bot is down', 'todo', 'low', '2026-04-28', NULL, 0, NULL),

-- Project 10 tasks
(10, 10, 'Onboarding checklist alpha', 'Create starter checklist for new members', 'in_progress', 'high', '2026-04-18', NULL, 0, NULL),
(10, 1, 'Welcome task templates', 'Prepare templates for first-week tasks', 'todo', 'medium', '2026-04-21', NULL, 0, NULL),
(10, 4, 'Training session script', 'Draft script for onboarding walkthrough', 'done', 'medium', '2026-04-09', 'training-script.docx', 0, NULL),
(10, 6, 'Access guide update', 'Update guide for project access and permissions', 'todo', 'high', '2026-04-20', NULL, 0, NULL),
(10, NULL, 'FAQ page seed', 'Seed common Q&A entries for new interns', 'todo', 'low', '2026-04-27', NULL, 0, NULL),

-- Project 11 tasks
(11, 1, 'Translate main README', 'Translate root README into Vietnamese', 'done', 'high', '2026-04-13', NULL, 0, NULL),
(11, 2, 'Glossary alignment', 'Align technical terms across all docs', 'in_progress', 'medium', '2026-04-19', NULL, 0, NULL),
(11, 3, 'UC document proofreading', 'Proofread use-case documents for consistency', 'todo', 'medium', '2026-04-22', NULL, 0, NULL),
(11, 4, 'Diagram caption translation', 'Translate captions in system diagrams', 'todo', 'low', '2026-04-25', NULL, 0, NULL),
(11, 10, 'Final doc QA pass', 'Final QA pass before packaging report', 'todo', 'high', '2026-04-20', NULL, 0, NULL),

-- Project 12 tasks (archived project, mixed archived status)
(12, 2, 'RC1 release notes', 'Compile release notes for archived RC1', 'done', 'high', '2026-04-08', 'rc1-release-notes.pdf', 1, '2026-04-09 09:10:00'),
(12, 1, 'Hotfix backlog snapshot', 'Snapshot pending hotfixes before archive', 'done', 'medium', '2026-04-07', NULL, 1, '2026-04-09 09:12:00'),
(12, 3, 'Regression summary', 'Summarize regression outcomes for RC1', 'done', 'medium', '2026-04-06', NULL, 1, '2026-04-09 09:13:00'),
(12, NULL, 'Postmortem draft', 'Draft retrospective notes for RC1 cycle', 'todo', 'low', '2026-04-30', NULL, 0, NULL);
